version: '3.8'

services:
    swp-postgres:
        image: postgres:16.2-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=CHOOSE_A_PASSWORD
            - POSTGRES_DB=swp
        ports:
            - 5432:5432
        volumes: 
            - ./db_data:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

